#!/usr/bin/env python3
"""Render gamma/delta-test-verdict.md from the delta-test JSON results.

Generated, not transcribed, so the verdict prose cannot drift from the harness.

Usage: python3 render_verdict.py <run_root> [<contract.json> [<authored.json>]]
"""
import json
import os
import sys

RR = sys.argv[1]
paths = [("γ (contract)", sys.argv[2] if len(sys.argv) > 2
          else os.path.join(RR, "gamma/delta-test-results-contract.json"))]
authored = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
    RR, "gamma/delta-test-results-authored.json")
if os.path.exists(authored):
    paths.append(("ε (authored)", authored))

L = ["# Wave γ — Delta-test verdict", "",
     "Generated by [`render_verdict.py`](./render_verdict.py) from the harness JSON.",
     "Spec: [`delta_test.md`](./delta_test.md). Harness: [`delta_test.py`](./delta_test.py).",
     ""]

for phase, p in paths:
    d = json.load(open(p))
    subs = d["detail"]
    union = d["artifact_union"]

    L += ["## Phase %s — `--mode %s`" % (phase, d["mode"]), "",
          "**Verdict: %s**" % d["verdict"], "",
          "| Subject | Score |", "|---------|-------|"]
    for s in subs:
        L.append("| %s | **%s** |" % (s["subject"], "%d/%d" % (s["score"], len(union))))
    L += [""]

    # capability matrix
    L += ["### Capability matrix", "",
          "| Artifact class | baseline_a<br>`cd-review` | baseline_b<br>`brainstorm` | composed |",
          "|----------------|:----:|:----:|:----:|"]
    for k in union:
        cells = []
        for s in subs:
            cells.append("✅" if s["artifacts"][k]["can_emit"] else "❌")
        L.append("| `%s` | %s | %s | %s |" % (k, cells[0], cells[1], cells[2]))
    L += [""]

    L += ["### Gaps the composition closes", "",
          "**Absent from `cd-review`, present in composed (%d):**" % len(d["capabilities_added_over_a"])]
    L += ["- `%s`" % k for k in d["capabilities_added_over_a"]] or ["- none"]
    L += ["", "**Absent from `brainstorm`, present in composed (%d):**" % len(d["capabilities_added_over_b"])]
    L += ["- `%s`" % k for k in d["capabilities_added_over_b"]] or ["- none"]
    L += [""]

    added_to_both = [k for k in d["capabilities_added_over_a"]
                     if k in d["capabilities_added_over_b"]]
    L += ["**Absent from BOTH parents (the genuinely new capability, %d):**" % len(added_to_both)]
    L += ["- `%s`" % k for k in added_to_both] or ["- none"]
    L += [""]

    L += ["### Admission conjuncts", "",
          "| Conjunct | Result |", "|----------|--------|",
          "| composed emits full 8-class union | %s |" % ("PASS" if d["composed_emits_full_union"] else "FAIL"),
          "| composed > baseline_a | %s |" % ("PASS" if d["composed_beats_baseline_a"] else "FAIL"),
          "| composed > baseline_b | %s |" % ("PASS" if d["composed_beats_baseline_b"] else "FAIL"),
          "| non-degenerate (adds to both) | %s |" % ("PASS" if d["non_degenerate"] else "FAIL"),
          "", "**→ %s**" % d["verdict"], ""]

    # audit trail
    L += ["<details>", "<summary>Evidence audit trail (every hit with file:line)</summary>", ""]
    for s in subs:
        L += ["#### %s" % s["subject"], "", "`%s`" % s["source"], ""]
        for k in union:
            a = s["artifacts"][k]
            if a["can_emit"]:
                L += ["- **`%s`** ✅" % k,
                      "  - port evidence — L%s: `%s`" % (a["port_evidence"]["line"], a["port_evidence"]["text"]),
                      "  - wave evidence — L%s: `%s`" % (a["wave_evidence"]["line"], a["wave_evidence"]["text"])]
            else:
                L += ["- **`%s`** ❌ — %s" % (k, "; ".join(a["missing"]))]
                if a["port_evidence"]:
                    L.append("  - (port present at L%s but no producing wave)" % a["port_evidence"]["line"])
                if a["wave_evidence"]:
                    L.append("  - (wave text at L%s but no port carries it)" % a["wave_evidence"]["line"])
        L += [""]
    L += ["</details>", ""]

open(os.path.join(RR, "gamma/delta-test-verdict.md"), "w").write("\n".join(L) + "\n")
print("wrote gamma/delta-test-verdict.md (%d phase(s))" % len(paths))
