import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Exigo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import ConvexClientProvider from "./ConvexClientProvider";

import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" className={`${geist.variable} dark antialiased tracking-tight`}>
        <body className="bg-black text-white min-h-screen">
          <ConvexClientProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
